
---
# global
sr: &fs 48000
windowSize: &wsize 480 # for spectrogram
hipass: False


Filtering: 
  sr: *fs
  order: 8
  lowcut: 300

Spectrogram:
  windowSize: *wsize
  overlap: 0
  sr: *fs
  windowType: hanning
  normalized: False
  logf: False

Indices:
  Parameters:
    - ACI
    - ADI50
    - AEI
    - BI
    - NDSI
    - HS
    - HT
    - H

  freq_BI: [2000,8000]
  freq_anthro: [1000,2000]
  freq_bio: [2000,11000]
  max_freq: 10000
  freq_step: 1000
  db_threshold: -50
  tol: 1.e-12
  windowSize: *wsize
  window: 10 # window for analysis in seconds (int)
  # nsamples is not known this is a guess
  # half_window = window*sr/(2*windowSize)
  # number of windows full = NOWF= nsamples / windowSize
  # number_of_windows = (NOWF-half_window)/half_window
  half_window: 500
  number_of_windows: 11
...
